trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '8.x'
  releaseBranchName: 'release'

stages:
- stage: Build
  displayName: Build the web application
  jobs: 
  - job: Build
    displayName: Build job
    pool:
      name: RetoAzure
      demands:
      - agent.name -equals MyAgent

    steps:
    - task: UseDotNet@2
      displayName: Use .NET SDK $(dotnetSdkVersion)
      inputs:
        version: $(dotnetSdkVersion)

    - task: UseNode@1
      displayName: Install Node.js 16.x
      inputs:
        version: 16.x

    - script: npm cache clean --force
      displayName: Clean NPM cache

    - task: Npm@1
      displayName: Run npm install
      inputs:
        verbose: false
        arguments: --no-optional

    - script: npx sass $(wwwrootDir) --no-source-map --style=compressed
      displayName: Compile Sass assets

    - script: npm install --global gulp-cli
      displayName: Install Gulp CLI globally

    - task: gulp@1
      displayName: Run gulp tasks

    - script: echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt
      displayName: Write build info
      workingDirectory: $(wwwrootDir)

    - task: DotNetCoreCLI@2
      displayName: Restore project dependencies
      inputs:
        command: restore
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build the project - $(buildConfiguration)
      inputs:
        command: build
        arguments: --no-restore --configuration $(buildConfiguration)
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Publish the project - $(buildConfiguration)
      inputs:
        command: publish
        projects: '$(System.DefaultWorkingDirectory)/**/Tailspin.SpaceGame.Web.csproj'
        publishWebProjects: false
        arguments: --no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)
        zipAfterPublish: true

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: 'Test'
  displayName: 'Deploy to the test environment'
  dependsOn: Build
  jobs:
  - job: RunUITests
    displayName: 'Run UI tests'
    pool:
      name: 'RetoAzure'
      demands:
         - agent.name -equals MyAgent
    steps: 
    - script: |
        echo "Verificando instalación de Google Chrome..."
        where chrome || (
          echo "Google Chrome no está instalado. Instalando..."
          powershell -Command "Start-Process msiexec.exe -ArgumentList '/i https://dl.google.com/chrome/install/latest/chrome_installer.exe /quiet /norestart' -Wait"
        )
      displayName: 'Verificar e instalar Google Chrome'

    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'
    
    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--configuration $(buildConfiguration)'
        projects: '$(System.DefaultWorkingDirectory)/**/*UITests.csproj'
    
    - task: DotNetCoreCLI@2
      displayName: 'Run UI tests - $(buildConfiguration)'
      inputs:
        command: 'test'
        arguments: '--no-build --configuration $(buildConfiguration)'
        publishTestResults: true
        projects: '$(System.DefaultWorkingDirectory)/**/*UITests.csproj'
